-- 2

SELECT employee_id 사원번호, emp_name 사원명, HIRE_DATE 입사일자, ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12) 근속년수
FROM employees
WHERE  ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12)>= 10
ORDER BY ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12);

-- 3

SELECT REPLACE(cust_main_phone_number, '-' , '/')
FROM CUSTOMERS;

-- 4

SELECT TRANSLATE(cust_main_phone_number, '0123456789', 'ABCDEFGHIJ')
FROM CUSTOMERS;

-- 5

SELECT CUST_NAME, CUST_YEAR_OF_BIRTH, 
        DECODE((TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH) / 10, 3,'30대',
                                                                    4, '40대',
                                                                    5, '50대','기타')generation
FROM customers;


SELECT CUST_NAME, CUST_YEAR_OF_BIRTH,
    CASE WHEN (TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)>=10 AND (TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)<20 THEN '10대'
        WHEN (TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)>=20 AND (TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)<30 THEN '20대'
        WHEN (TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)>=30 AND (TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)<40 THEN '30대'
        WHEN (TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)>=40 AND (TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)<50 THEN '40대'
        WHEN (TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)>=50 AND (TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)<60 THEN '50대'
        WHEN (TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)>=60 AND (TO_CHAR(SYSDATE, 'YYYY') - CUST_YEAR_OF_BIRTH)<70 THEN '60대'
        ELSE '70대 이상'
    END AS generation
FROM customers;
    
    
SELECT (TO_CHAR(SYSDATE, 'YYYY') - 1987)/10
FROM DUAL;

